### ISSUE TITLE
 Unexpectedly found nil while unwrapping an Optional value Lost connection to device.

### ISSUE THREAD

**Issue by ravindudhananjaya** [WebEferen/flutter_wallet_card#13]
flutter_wallet_card/SwiftFlutterWalletCardPlugin.swift:29: Fatal error: Unexpectedly found nil while unwrapping an Optional value
Lost connection to device.

**Comment by WebEferen** [comment]
Hi @ravindudhananjaya, will check this issue.
Can you provide the steps how to reproduce this bug?

**Comment by WebEferen** [comment]
Closed due to inactivity.
