### ISSUE TITLE
Add credit card to any Wallet

### ISSUE THREAD

**Issue by arielCloudX** [WebEferen/flutter_wallet_card#16]
Hi, 
I would like to know if this package can be used to add credit cards to Apple Wallet or if it is only for Tickets or something else.

I look forward to your response, thank you very much.

**Comment by WebEferen** [comment]
Hi @arielCloudX,
Worth checking: If the card is using NFC then it might be possible to add it to the wallet.

Unfortunately AFAIK there is no possibility to add credit cards into Wallet as they need to use internal Apple chip for verification and they need to be stored in secure form (apple itself is using their own "proxy" that hides real card details).
