### ISSUE TITLE
Handle .pkpasses

### ISSUE THREAD

**Issue by StephanWalters** [WebEferen/flutter_wallet_card#17]
This method works when handling a passkit file with one one pass (.pkpass) extensions, but is unable to handle a passkit file that has multiple passes (.pkpasses extension). Is there any support to handle a pkpass that has more than one pass in it?
```
import 'package:flutter_wallet_card/flutter_wallet_card.dart';

/// It returns [PasskitFile] object
final passkitFile = await FlutterWalletCard.generateFromFile(
  id: 'example-pass',
  file: File('path-to-file.pkpass'),
);
```

**Comment by WebEferen** [comment]
At this moment, there is no way to handle .pkpasses files (will need to do further investigation of how the .pkpassess are structured). 

I will add it in the upcoming version if there will be no bigger hassle with the structure).
