### ISSUE TITLE
Generate from scratch 

### ISSUE THREAD

**Issue by Salam-pc** [WebEferen/flutter_wallet_card#9]
can you pls add an example for Generate from scratch method . i'm getting false for FlutterWalletCard.addPassKit(samplefile) and don't know where is the issue

**Comment by WebEferen** [comment]
Hey, sure. Will add it today by the EOD :)
@Salam-pc

**Comment by WebEferen** [comment]
**Steps to generate signatures/keys/certificates from scratch:**

1. Create Signer class
For that you will need to have two files which can be created and exported using Apple's KeyChain or OpenSSL.

```dart
  final signer = Signer(
    wwdrPem: wwdrPem, // this is File class that represents wwdrPem key
    certificateP12: certP12, // this is File class representing .p12 key
    directory: certificates, // output directory where signer should create signature in the future
  );
```

2. Generate required certificates (cert + key)
For that you need to call two signer methods:

```dart
await Future.wait([
    signer.generateKey(),
     signer.generateCertificate(), // there is also a possibility to specify password key (argument)
]);
```

3. Generate signature
Generate signature that will sign all the generated files

Example manifest file (it is containing sha1 hashes of the files to verify integrity)
https://github.com/WebEferen/flutter_wallet_card/blob/master/test/fixtures/example_passkit/manifest.json

For manifest generation you can also use `Creators` helper (and it's create manifest method):
https://github.com/WebEferen/flutter_wallet_card/blob/0b65916ba0d22844bd6cee7ea5e0b825384b6673/lib/core/creators.dart#L21

```dart
final manifest = File(....);
await signer.generateSignature(manifest: manifest);
```

4. With generated signature, instantiate Passkit class:

```dart
final outputDirectory = Directory(...);
final passkit = Passkit(directoryName: outputDirectory.path);

final generated = await passkit.generate(
          id: 'some_id',
          pkpass: pkpass, // You should also have pkpass file already generated
          directory: outputDirectory,
          signature: signaturePath, // Path to the previously generated signature
          manifest: manifestPath, // Path to the previously generated manifest
          passkitPass: passkitPath, // Path to the passkit file
        );
```

For reference you can follow the test suite (to see how it works under the hood):
- https://github.com/WebEferen/flutter_wallet_card/blob/master/test/passkit_test.dart
- https://github.com/WebEferen/flutter_wallet_card/blob/master/test/signer_test.dart
- https://github.com/WebEferen/flutter_wallet_card/blob/master/test/creators_test.dart

Best,
Mike.
